[platformio]
src_dir = src
include_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_ldf_mode = deep
lib_deps = 
  https://github.com/ThingPulse/esp8266-oled-ssd1306/archive/refs/tags/4.6.1.zip
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  bblanchon/ArduinoJson